from django.urls import path
from . import views
from .auth_views import CustomTokenObtainPairView
from rest_framework_simplejwt.views import (
    TokenRefreshView,
)

urlpatterns = [
    path("", views.home, name="home"),
    path("health/", views.health, name="health"),
    path("register/", views.register_user, name="register_user"),
    path("login/", views.login_user, name="login_user"),
    path("auth/activate/", views.activate_account, name="activate_account"),
    path("auth/resend-activation/", views.resend_activation, name="resend_activation"),
    path("auth/password-reset-request/", views.password_reset_request, name="password_reset_request"),
    path("auth/password-reset-verify/<str:token>/", views.password_reset_verify, name="password_reset_verify"),
    path("auth/password-reset-confirm/", views.password_reset_confirm, name="password_reset_confirm"),
    path("token/", CustomTokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("profiles/", views.profile_list, name="profile_list"),
    path("profiles/me/", views.profile_own, name="profile_own"),
    path("profiles/<int:user_id>/", views.profile_detail, name="profile_detail"),
    path("users/<int:user_id>/public/", views.public_profile_view, name="public_profile_view"),
    path("ratings/", views.ratings_list_create, name="ratings_list_create"),
    path("ratings/<int:handshake_id>/", views.rating_create_for_handshake, name="rating_create_for_handshake"),
    path("ratings/user/<int:user_id>/", views.ratings_by_user, name="ratings_by_user"),
    path("ratings/handshake/<int:handshake_id>/", views.ratings_by_handshake, name="ratings_by_handshake"),
    path("badges/", views.badges_list, name="badges_list"),
    path("offers/", views.offers_list_create, name="offers_list_create"),
    path("offers/<int:offer_id>/", views.offer_detail, name="offer_detail"),
    path("offers/<int:offer_id>/edit/", views.offer_edit, name="offer_edit"),
    path("offers/<int:offer_id>/delete/", views.offer_delete, name="offer_delete"),
    path("offers/<int:offer_id>/location-diagnostic/", views.location_diagnostic, name="location_diagnostic"),
    path("requests/", views.requests_list_create, name="requests_list_create"),
    path("requests/<int:request_id>/", views.request_detail, name="request_detail"),
    path("requests/<int:request_id>/edit/", views.request_edit, name="request_edit"),
    path("requests/<int:request_id>/delete/", views.request_delete, name="request_delete"),
    path("handshakes/", views.handshakes_list_create, name="handshakes_list_create"),
    path("handshakes/<int:handshake_id>/accept/", views.handshake_accept, name="handshake_accept"),
    path("handshakes/<int:handshake_id>/decline/", views.handshake_decline, name="handshake_decline"),
    path("handshakes/<int:handshake_id>/confirm-provider/", views.handshake_confirm_provider, name="handshake_confirm_provider"),
    path("handshakes/<int:handshake_id>/confirm-seeker/", views.handshake_confirm_seeker, name="handshake_confirm_seeker"),
    path("timebank/", views.timebank_view, name="timebank_view"),
    path("timebank/balance/", views.timebank_balance, name="timebank_balance"),
    path("transactions/", views.transactions_list, name="transactions_list"),
    path("questions/", views.questions_list_create, name="questions_list_create"),
    path("questions/<int:question_id>/answer/", views.question_answer, name="question_answer"),
    path("messages/", views.messages_list_create, name="messages_list_create"),
    path("tags/", views.tags_list, name="tags_list"),
    path("tags/wikidata/", views.tags_wikidata, name="tags_wikidata"),
    path("forum/topics/", views.forum_topics_list_create, name="forum_topics_list_create"),
    path("forum/topics/<int:topic_id>/", views.forum_topic_detail, name="forum_topic_detail"),
    path("forum/topics/<int:topic_id>/reply/", views.forum_topic_reply, name="forum_topic_reply"),
    path("forum/topics/<int:topic_id>/delete/", views.forum_topic_delete, name="forum_topic_delete"),
    path("forum/replies/<int:reply_id>/delete/", views.forum_reply_delete, name="forum_reply_delete"),
    path("inbox/pending-handshakes/", views.inbox_pending_handshakes, name="inbox_pending_handshakes"),
    path("inbox/unread-messages/", views.inbox_unread_messages, name="inbox_unread_messages"),
    path("inbox/conversations/", views.inbox_conversations, name="inbox_conversations"),
    # Admin utilities
    path("admin/load-realistic-posts/", views.load_realistic_posts_admin, name="load_realistic_posts_admin"),
]
