# DigitalOcean App Platform configuration
# This file helps DO understand your app structure
# You can also configure via DO web UI instead

name: the-hive
region: nyc

services:
  - name: api
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    
    run_command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8080 --workers 3 --timeout 120
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs  # Free tier: basic-xxs
    
    # Source directory
    source_dir: /
    build_command: docker build -t the-hive-api .
    
    # Working directory for the app
    dockerfile_path: Dockerfile
    
    http_port: 8000
    routes:
      - path: /
    
    # Environment variables (set these in DO dashboard instead of here for security)
    envs:
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings
      - key: PYTHONUNBUFFERED
        value: "1"
    
    # Health check
    health_check:
      http_path: /api/health/
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

databases:
  - name: the-hive-db
    engine: PG
    production: false
    version: "16"


