# Generated by Django 5.2.7 on 2025-11-11 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_offer_category_remove_request_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='handshake',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('settled', 'Settled'), ('declined', 'Declined')], default='proposed', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='handshake',
            constraint=models.UniqueConstraint(fields=('provider', 'seeker', 'offer'), name='unique_offer_handshake'),
        ),
    ]
