# Generated by Django 5.2.7 on 2025-11-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_offer_created_at_offer_status_offer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='available_slots',
            field=models.TextField(blank=True, help_text='JSON array of available date/time slots', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='available_slots',
            field=models.TextField(blank=True, help_text='JSON array of available date/time slots', null=True),
        ),
    ]
