# Generated by Django 5.2.7 on 2025-12-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_rating_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='handshake',
            name='unique_offer_handshake',
        ),
        migrations.AddField(
            model_name='rating',
            name='tags',
            field=models.JSONField(default=list, help_text='Array of tag strings (max 3)'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
    ]
